DISTANCE_TOLERANCE = 0.005
SIMULATION_SPEED = 100
MAX_SIMULATION_TIME =1000
NUM_ACTORS=1
ACTOR_SPEED=1
LAMBDA=0.8
SERVICE_TIME=0
TICK_TIME = 0.01

POLICY_NAME = "RND_NO_RETURN"
POLICY_NAME = "TSP"
# POLICY_NAME = "TSP_MOD"

# simulation environment configs

SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 1000
MARGIN = 150